-- Penacony_GreatPeople
-- Author: Nwflower
-- DateCreated: 2025-5-14 13:31:42
--------------------------------------------------------------
--================
-- 伟人：知更鸟
--================
INSERT INTO Types (Type, Kind)
VALUES	('GREAT_PERSON_CLASS_ROBIN', 'KIND_GREAT_PERSON_CLASS'),
		('GREAT_PERSON_INDIVIDUAL_ROBIN_0',	'KIND_GREAT_PERSON_INDIVIDUAL'),
		('GREAT_PERSON_INDIVIDUAL_ROBIN_1',	'KIND_GREAT_PERSON_INDIVIDUAL'),
		('GREAT_PERSON_INDIVIDUAL_ROBIN_2',	'KIND_GREAT_PERSON_INDIVIDUAL'),
		('GREAT_PERSON_INDIVIDUAL_ROBIN_3',	'KIND_GREAT_PERSON_INDIVIDUAL');

INSERT INTO Types (Type, Kind)
VALUES	('PSEUDOYIELD_GPP_ROBIN',			'KIND_PSEUDOYIELD');

INSERT INTO PseudoYields (PseudoYieldType, DefaultValue)
VALUES	('PSEUDOYIELD_GPP_ROBIN', 0.5);

INSERT INTO GreatPersonClasses
(GreatPersonClassType, Name, UnitType, DistrictType, AvailableInTimeline, GenerateDuplicateIndividuals, PseudoYieldType, IconString, ActionIcon)
VALUES
('GREAT_PERSON_CLASS_ROBIN',
 'LOC_GREAT_PERSON_CLASS_MUSICIAN_NAME',
 'UNIT_GREAT_MUSICIAN',
 'DISTRICT_CITY_CENTER',
 0,
 1,
 'PSEUDOYIELD_GPP_ROBIN',
 '[ICON_GreatMusician]',
 'ICON_UNITOPERATION_MUSICIAN_ACTION');

INSERT INTO GreatPersonIndividuals (GreatPersonIndividualType, Name, GreatPersonClassType, EraType, Gender, ActionCharges)
VALUES
('GREAT_PERSON_INDIVIDUAL_ROBIN_0',
 'LOC_LEADER_NW_ROBIN_NAME',
 'GREAT_PERSON_CLASS_ROBIN',
 'ERA_ANCIENT',
 'F',
 0),
('GREAT_PERSON_INDIVIDUAL_ROBIN_1',
 'LOC_LEADER_NW_ROBIN_NAME',
 'GREAT_PERSON_CLASS_ROBIN',
 'ERA_ANCIENT',
 'F',
 0),
('GREAT_PERSON_INDIVIDUAL_ROBIN_2',
 'LOC_LEADER_NW_ROBIN_NAME',
 'GREAT_PERSON_CLASS_ROBIN',
 'ERA_ANCIENT',
 'F',
 0),
('GREAT_PERSON_INDIVIDUAL_ROBIN_3',
 'LOC_LEADER_NW_ROBIN_NAME',
 'GREAT_PERSON_CLASS_ROBIN',
 'ERA_ANCIENT',
 'F',
 0);

INSERT INTO CivilopediaPageGroupExcludes(SectionId, PageGroupId)
VALUES 	('GREATPEOPLE', 'GREAT_PERSON_CLASS_ROBIN');