-- Penacony_Civilization
-- Author: Nwflower
-- DateCreated: 2025-5-9 15:50:48
--------------------------------------------------------------
INSERT INTO Types
(Type,								Kind)
VALUES
('CIVILIZATION_NW_PENACONY',		'KIND_CIVILIZATION'),
('TRAIT_CIVILIZATION_SINKDREAM',	'KIND_TRAIT'),
('TRAIT_UNIT_DREAM_BUILDER',		'KIND_TRAIT'),
('TRAIT_PROJECT_HARMONY_CEREMONY',	'KIND_TRAIT'),
('TRAIT_IMPROVEMENT_DREAM_POOL',	'KIND_TRAIT');

INSERT INTO Civilizations
(CivilizationType,		Name,		Description,		Adjective,		RandomCityNameDepth,		StartingCivilizationLevelType,		Ethnicity)
VALUES
('CIVILIZATION_NW_PENACONY',	'LOC_CIVILIZATION_NW_PENACONY_NAME',	'LOC_CIVILIZATION_NW_PENACONY_DESCRIPTION',	'LOC_CIVILIZATION_NW_PENACONY_ADJECTIVE',	15,		'CIVILIZATION_LEVEL_FULL_CIV',	'ETHNICITY_ASIAN');

INSERT INTO CityNames
(CivilizationType,                    CityName)
VALUES
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_GOLD'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_1'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_2'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_3'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_4'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_5'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_6'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_7'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_8'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_9'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_10'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_11'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_12'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_13'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_14'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_15'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_16'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_17'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_18'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_19'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_20'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_21'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_22'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_23'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_24'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_25'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_26'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_27'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_28'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_29'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_30'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_31'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_32'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_33'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_34'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_35'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_36'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_37'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_38'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_39'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_40'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_41'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_42'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_43'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_44'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_45'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_46'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_47'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_48'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_49'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_50'),
('CIVILIZATION_NW_PENACONY',          'LOC_CITY_NAME_NW_PENACONY_51');


INSERT INTO CivilizationCitizenNames	
(CivilizationType,		CitizenName,	Female,		Modern)
SELECT
'CIVILIZATION_NW_PENACONY',	CitizenName,	Female,		Modern
FROM CivilizationCitizenNames WHERE CivilizationType = 'CIVILIZATION_FRANCE';
	
INSERT INTO CivilizationLeaders
(CivilizationType,					LeaderType,				CapitalName)
VALUES
('CIVILIZATION_NW_PENACONY',				'LEADER_NW_ROBIN',	'LOC_CITY_NAME_NW_PENACONY_GOLD'),
('CIVILIZATION_NW_PENACONY',				'LEADER_NW_SUNDAY',	'LOC_CITY_NAME_NW_PENACONY_GOLD');

INSERT INTO Traits
(TraitType,							Name,									Description)
VALUES
('TRAIT_CIVILIZATION_SINKDREAM',	'LOC_TRAIT_CIVILIZATION_SINKDREAM_NAME',	'LOC_TRAIT_CIVILIZATION_SINKDREAM_DESCRIPTION'),
('TRAIT_UNIT_DREAM_BUILDER',	null,									null),
('TRAIT_PROJECT_HARMONY_CEREMONY',		null,									null),
('TRAIT_IMPROVEMENT_DREAM_POOL',			null,									null);

INSERT INTO CivilizationTraits
(TraitType,							CivilizationType)
VALUES
('TRAIT_CIVILIZATION_SINKDREAM',	'CIVILIZATION_NW_PENACONY'),
('TRAIT_UNIT_DREAM_BUILDER',	'CIVILIZATION_NW_PENACONY'),
('TRAIT_PROJECT_HARMONY_CEREMONY',			'CIVILIZATION_NW_PENACONY'),
('TRAIT_IMPROVEMENT_DREAM_POOL',			'CIVILIZATION_NW_PENACONY');

INSERT INTO StartBiasResources
(CivilizationType,					ResourceType,				Tier)
VALUES
('CIVILIZATION_NW_PENACONY',				'RESOURCE_TOBACCO',			3),
('CIVILIZATION_NW_PENACONY',				'RESOURCE_SUGAR',			3);