-- Penacony_Leader
-- Author: Nwflower
-- DateCreated: 2025-5-9 16:22:20
--------------------------------------------------------------
--=============
--ROBIN
--=============
INSERT INTO Types
    (Type, Kind)
Values ('LEADER_NW_ROBIN', 'KIND_LEADER'),
       ('TRAIT_LEADER_FLY_TO_SKY_TOGETHER', 'KIND_TRAIT'),
       ('TRAIT_GREATWORK_ROBIN_0', 'KIND_TRAIT'),
       ('TRAIT_GREATWORK_ROBIN_1', 'KIND_TRAIT'),
       ('TRAIT_GREATWORK_ROBIN_2', 'KIND_TRAIT'),
       ('TRAIT_GREATWORK_ROBIN_3', 'KIND_TRAIT');

INSERT INTO Leaders
    (LeaderType, Name, InheritFrom, Sex, SceneLayers)
Values ('LEADER_NW_ROBIN', 'LOC_LEADER_NW_ROBIN_NAME', 'LEADER_DEFAULT', 'Female', 4);

INSERT INTO LeaderQuotes
    (LeaderType, Quote)
VALUES ('LEADER_NW_ROBIN', 'LOC_LEADER_NW_ROBIN_QUOTE');

INSERT INTO LoadingInfo
    (LeaderType, ForegroundImage, BackgroundImage, PlayDawnOfManAudio)
VALUES ('LEADER_NW_ROBIN', 'IMG_PNG_LEADER_NW_ROBIN', 'IMG_PNG_CIVILIZATION_NW_PENACONY_BACKGROUND_SELECTION', 1);

INSERT INTO DiplomacyInfo
    (Type, BackgroundImage)
VALUES ('LEADER_NW_ROBIN', 'IMG_PNG_CIVILIZATION_NW_PENACONY_BACKGROUND');

INSERT INTO Traits
    (TraitType, Name, Description)
VALUES ('TRAIT_LEADER_FLY_TO_SKY_TOGETHER', 'LOC_TRAIT_LEADER_FLY_TO_SKY_TOGETHER_NAME',
        'LOC_TRAIT_LEADER_FLY_TO_SKY_TOGETHER_DESCRIPTION'),
    ('TRAIT_GREATWORK_ROBIN_0', 'LOC_GREATWORK_ROBIN_0_NAME',
        'LOC_GREATWORK_ROBIN_0_DIS'),
    ('TRAIT_GREATWORK_ROBIN_1', 'LOC_GREATWORK_ROBIN_1_NAME',
        'LOC_GREATWORK_ROBIN_1_DIS'),
    ('TRAIT_GREATWORK_ROBIN_2', 'LOC_GREATWORK_ROBIN_2_NAME',
        'LOC_GREATWORK_ROBIN_2_DIS'),
    ('TRAIT_GREATWORK_ROBIN_3', 'LOC_GREATWORK_ROBIN_3_NAME',
        'LOC_GREATWORK_ROBIN_3_DIS');

INSERT INTO LeaderTraits
    (LeaderType, TraitType)
VALUES ('LEADER_NW_ROBIN', 'TRAIT_LEADER_FLY_TO_SKY_TOGETHER'),
       ('LEADER_NW_ROBIN', 'TRAIT_GREATWORK_ROBIN_0'),
       ('LEADER_NW_ROBIN', 'TRAIT_GREATWORK_ROBIN_1'),
       ('LEADER_NW_ROBIN', 'TRAIT_GREATWORK_ROBIN_2'),
       ('LEADER_NW_ROBIN', 'TRAIT_GREATWORK_ROBIN_3');

INSERT INTO HistoricalAgendas
    (LeaderType, AgendaType)
VALUES ('LEADER_NW_ROBIN', 'AGENDA_LEADER_NW_ROBIN');

INSERT INTO Agendas
    (AgendaType, Name, Description)
VALUES ('AGENDA_LEADER_NW_ROBIN', 'LOC_AGENDA_LEADER_NW_ROBIN_NAME', 'LOC_AGENDA_LEADER_NW_ROBIN_DESCRIPTION');

--=============
--SUNDAY
--=============
INSERT INTO Types
    (Type, Kind)
Values ('LEADER_NW_SUNDAY', 'KIND_LEADER'),
       ('TRAIT_LEADER_POEM_CHOIR', 'KIND_TRAIT'); --万象仃伶

INSERT INTO Leaders
    (LeaderType, Name, InheritFrom, Sex, SceneLayers)
Values ('LEADER_NW_SUNDAY', 'LOC_LEADER_NW_SUNDAY_NAME', 'LEADER_DEFAULT', 'Male', 4);

INSERT INTO LeaderQuotes
    (LeaderType, Quote)
VALUES ('LEADER_NW_SUNDAY', 'LOC_LEADER_NW_SUNDAY_QUOTE');

INSERT INTO LoadingInfo
    (LeaderType, ForegroundImage, BackgroundImage, PlayDawnOfManAudio)
VALUES ('LEADER_NW_SUNDAY', 'IMG_PNG_LEADER_NW_SUNDAY', 'IMG_PNG_CIVILIZATION_NW_PENACONY_BACKGROUND_SELECTION', 1);

INSERT INTO DiplomacyInfo
    (Type, BackgroundImage)
VALUES ('LEADER_NW_SUNDAY', 'IMG_PNG_CIVILIZATION_NW_PENACONY_BACKGROUND');

INSERT INTO Traits
    (TraitType, Name, Description)
VALUES ('TRAIT_LEADER_POEM_CHOIR', 'LOC_TRAIT_LEADER_POEM_CHOIR_NAME', 'LOC_TRAIT_LEADER_POEM_CHOIR_DESCRIPTION');

INSERT INTO LeaderTraits
    (LeaderType, TraitType)
VALUES ('LEADER_NW_SUNDAY', 'TRAIT_LEADER_POEM_CHOIR');

INSERT INTO HistoricalAgendas
    (LeaderType, AgendaType)
VALUES ('LEADER_NW_SUNDAY', 'AGENDA_LEADER_NW_SUNDAY');

INSERT INTO Agendas
    (AgendaType, Name, Description)
VALUES ('AGENDA_LEADER_NW_SUNDAY', 'LOC_AGENDA_LEADER_NW_SUNDAY_NAME', 'LOC_AGENDA_LEADER_NW_SUNDAY_DESCRIPTION');
