-- KNM_Herta_Config
-- Author: Konomi
-- DateCreated: 5/21/2023 8:54:25
--------------------------------------------------------------
INSERT INTO Players
(Domain, CivilizationType, LeaderType, CivilizationName, CivilizationIcon, LeaderName, LeaderIcon,
 CivilizationAbilityName, CivilizationAbilityDescription, CivilizationAbilityIcon, LeaderAbilityName,
 LeaderAbilityDescription, LeaderAbilityIcon, Portrait, PortraitBackground)
VALUES ('Players:Expansion2_Players', 'CIVILIZATION_KNM_HERTA_SPACE_STATION', 'LEADER_KNM_HERTA',
        'LOC_CIVILIZATION_KNM_HERTA_SPACE_STATION_NAME', 'ICON_CIVILIZATION_KNM_HERTA_SPACE_STATION',
        'LOC_LEADER_KNM_HERTA_NAME', 'ICON_LEADER_KNM_HERTA', 'LOC_TRAIT_CIVILIZATION_KNM_HERTA_SPACE_STATION_NAME',
        'LOC_TRAIT_CIVILIZATION_KNM_HERTA_SPACE_STATION_DESCRIPTION', 'ICON_CIVILIZATION_KNM_HERTA_SPACE_STATION',
        'LOC_TRAIT_LEADER_KNM_HERTA_NAME', 'LOC_TRAIT_LEADER_KNM_HERTA_DESCRIPTION', 'ICON_LEADER_KNM_HERTA',
        'Herta_Portrait', 'Herta_Portrait_B'),
       ('Players:Expansion2_Players', 'CIVILIZATION_KNM_HERTA_SPACE_STATION', 'LEADER_KNM_ASTA',
        'LOC_CIVILIZATION_KNM_HERTA_SPACE_STATION_NAME', 'ICON_CIVILIZATION_KNM_HERTA_SPACE_STATION',
        'LOC_LEADER_KNM_ASTA_NAME', 'ICON_LEADER_KNM_ASTA', 'LOC_TRAIT_CIVILIZATION_KNM_HERTA_SPACE_STATION_NAME',
        'LOC_TRAIT_CIVILIZATION_KNM_HERTA_SPACE_STATION_DESCRIPTION', 'ICON_CIVILIZATION_KNM_HERTA_SPACE_STATION',
        'LOC_TRAIT_LEADER_KNM_ASTA_NAME', 'LOC_TRAIT_LEADER_KNM_ASTA_DESCRIPTION', 'ICON_LEADER_KNM_ASTA',
        'Asta_Portrait', 'Herta_Portrait_B');

INSERT INTO PlayerItems
(Domain, CivilizationType, LeaderType, Type, Name, Description, Icon, SortIndex)
VALUES ('Players:Expansion2_Players', 'CIVILIZATION_KNM_HERTA_SPACE_STATION', 'LEADER_KNM_HERTA',
        'IMPROVEMENT_KNM_RAILWAY_PLATFORM', 'LOC_TRAIT_IMPROVEMENT_KNM_RAILWAY_PLATFORM_NAME',
        'LOC_TRAIT_IMPROVEMENT_KNM_RAILWAY_PLATFORM_DESCRIPTION', 'ICON_IMPROVEMENT_KNM_RAILWAY_PLATFORM', 10),
       ('Players:Expansion2_Players', 'CIVILIZATION_KNM_HERTA_SPACE_STATION', 'LEADER_KNM_HERTA',
        'UNIT_KNM_HERTA_PUPPET', 'LOC_TRAIT_UNIT_KNM_HERTA_PUPPET_NAME', 'LOC_TRAIT_UNIT_KNM_HERTA_PUPPET_DESCRIPTION',
        'ICON_UNIT_KNM_HERTA_PUPPET', 15),
       ('Players:Expansion2_Players', 'CIVILIZATION_KNM_HERTA_SPACE_STATION', 'LEADER_KNM_ASTA',
        'IMPROVEMENT_KNM_RAILWAY_PLATFORM', 'LOC_TRAIT_IMPROVEMENT_KNM_RAILWAY_PLATFORM_NAME',
        'LOC_TRAIT_IMPROVEMENT_KNM_RAILWAY_PLATFORM_DESCRIPTION', 'ICON_IMPROVEMENT_KNM_RAILWAY_PLATFORM', 10),
       ('Players:Expansion2_Players', 'CIVILIZATION_KNM_HERTA_SPACE_STATION', 'LEADER_KNM_ASTA',
        'UNIT_KNM_HERTA_PUPPET', 'LOC_TRAIT_UNIT_KNM_HERTA_PUPPET_NAME', 'LOC_TRAIT_UNIT_KNM_HERTA_PUPPET_DESCRIPTION',
        'ICON_UNIT_KNM_HERTA_PUPPET', 15);
