-- KNM_Herta_zh_CN
-- Author: Konomi
-- DateCreated: 5/21/2023 9:02:56
--------------------------------------------------------------

INSERT INTO LocalizedText
		(Language,		Tag,																Text)
VALUES	('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_1_NAME',							'支援舱段'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_1_FAITH_GOLD_DESCRIPTION',			'位于市中心时，城市+3 [ICON_Gold] 金币。'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_1_CULTURE_DESCRIPTION',				'位于市中心时，城市+1 [ICON_Production] 生产力。'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_1_FOOD_PRODUCTION_DESCRIPTION',		'位于市中心时，城市+1 [ICON_Food] 食物。'),

		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_2_NAME',							'收容舱段'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_2_MERCHANT_PROPHET_DESCRIPTION',	'位于市中心时，城市每回合+1 [ICON_GreatProphet] 大预言家点数。'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_2_SCIENTIST_DESCRIPTION',			'位于市中心时，城市每回合+1 [ICON_GreatScientist] 大科学家点数。'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_2_WRITER_ARTIST_DESCRIPTION',		'位于市中心时，城市每回合+1 [ICON_GreatWriter] 大作家点数'),

		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_3_NAME',							'基座舱段'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_3_FAITH_GOLD_DESCRIPTION',			'位于市中心时，城市+5% [ICON_Faith] 信仰。'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_3_SCIENCE_DESCRIPTION',				'位于市中心时，城市+5% [ICON_Science] 科技。'),
		('zh_Hans_CN',	'LOC_PROMOTION_KNM_HERTA_PUPPET_3_CULTURE_DESCRIPTION',				'位于市中心时，城市+5% [ICON_Culture] 文化。'),

		('zh_Hans_CN',	'LOC_UNIT_KNM_HERTA_PURCHASE_TECH',									'是否花费{1_Num} [ICON_Gold] 金币解锁{2_Str}？'),
		('zh_Hans_CN',	'LOC_UNIT_KNM_HERTA_PURCHASE_TECH_NO_BALANCE',						'需要{1_Num} [ICON_Gold] 金币解锁{2_Str}，国库不足。'),
		('zh_Hans_CN',	'LOC_NOTIFICATION_KNM_HERTA_HOW_TO_PURCHASE_DESC',					'如果需要解锁科技，请在科技树面板中右击相应科技。'),

		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION0',							'办公室'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION1',							'监察域'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION2',							'核心通路'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION3',							'监控室'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION4',							'接待中心'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION5',							'控制中心'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION6',							'中庭'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION7',							'无明之间'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION8',							'电力室'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION9',							'备件库房'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION10',							'医疗舱室'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION11',							'星语厅'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION12',							'万有应物科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION13',							'银河法政科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION14',							'寰宇地概科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION15',							'星域界种科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION16',							'维修科室'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION17',							'餐厅'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION18',							'防卫科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION19',							'光渊密卷科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION20',							'服务科'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION21',							'集散中心'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION22',							'温床'),
		('zh_Hans_CN',	'LOC_CITY_NAME_KNM_HERTA_SPACE_STATION23',							'药物制备间'),

		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION1',						'伦纳德'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION2',						'温明德'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION3',						'古恩'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION4',						'洛奇'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION5',						'荣仓终'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION6',						'阿兰'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION7',						'莱斯莉'),
		('zh_Hans_CN',	'LOC_CITIZEN_NAME_KNM_HERTA_SPACE_STATION8',						'希拉'),

		('zh_Hans_CN',	'LOC_LOADING_INFO_LEADER_KNM_HERTA',															'人们曾说空中楼阁永远无法建成，但您，黑塔，却有一座天空之上的家园。您在科学技术领域慧眼如炬，假以时日人们终将理解您胜于时代的智慧。派出您的人偶调度事务进展，让人们知道它们即是您的化身。站上飞船月台，出发探索远方吧，为您的空间站取回新的奇物。'),
		('zh_Hans_CN',	'LOC_AGENDA_KNM_HERTA_NAME',																	'我就是这样女子'),
		('zh_Hans_CN',	'LOC_AGENDA_KNM_HERTA_DESCRIPTION',																'对 [ICON_Science] 科技值和 [ICON_Culture] 文化值领先的文明很友好。讨厌 [ICON_Science] 科技值和 [ICON_Culture] 文化值落后的文明。'),
		('zh_Hans_CN',	'LOC_LEADER_KNM_HERTA_QUOTE',																	'我已经够完美了，还有什么事要做？我当然可以再写几本书…但这于我何用，我为什么还要白费这些力气？'),
		('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_LEADER_KNM_HERTA_ANY',													'我是黑塔，现在很忙，这是远程人偶自动应答模式：你好，你好，大家好，祝你拥有愉快的一天，再见。'),
		('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_KNM_HERTA_ANY',									'今天来我这儿一起做研究吧——我研究你。'),
		('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_KNM_HERTA_ANY',							'这里会有我感兴趣的东西么？我不信。'),
		('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_KNM_HERTA_ANY',									'啊？行吧。'),
		('zh_Hans_CN',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_KNM_HERTA_ANY',									'今天对你失去兴趣了，明天再说。'),
		('zh_Hans_CN',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_KNM_HERTA_ANY',											'嘿，我有好事找你。我有一大堆和你有关的计划。'),
		('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_KNM_HERTA_ANY',								'行吧。'),
		('zh_Hans_CN',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_KNM_HERTA_ANY',								'空间站如此井井有条，也不是我朋友帮忙打理的。朋友重要吗？'),
		('zh_Hans_CN',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_KNM_HERTA_ANY',										'我能拿你做点研究吗？本天才对你有点兴趣。'),
		('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_KNM_HERTA_ANY',									'速来我的办公室！等你！'),
		('zh_Hans_CN',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_KNM_HERTA_ANY',									'哼。等我失去热情了，你求我我都不研究你咯。'),
		('zh_Hans_CN',	'LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_KNM_HERTA_ANY',											'妙哉，求知就是科学的基础。我想给你个机会参与一个大项目，我们一起行动。'),
		('zh_Hans_CN',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_KNM_HERTA_ANY',											'能不能安静一点！'),
		('zh_Hans_CN',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_KNM_HERTA_ANY',												'既不解题又不写稿，那就别怪自己的人生无趣咯？（谴责你）'),
		('zh_Hans_CN',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_KNM_HERTA_ANY',										'怎么收拾你，全看我心情。'),
		('zh_Hans_CN',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_KNM_HERTA_ANY',											'拿出你的看家本事，我的时间很宝贵。'),
		('zh_Hans_CN',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KNM_HERTA_ANY',												'断开…连接……'),
		('zh_Hans_CN',	'LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_KNM_HERTA_ANY',												'{LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KNM_HERTA_ANY}'),
		('zh_Hans_CN',	'LOC_DIPLO_KUDO_EXIT_LEADER_KNM_HERTA_ANY',														'你还挺有天分，我蛮中意的。我现在感兴趣，什么都愿意迁就。'),
		('zh_Hans_CN',	'LOC_DIPLO_KUDO_LEADER_KNM_HERTA_LEADS_PROGRESS',												'黑塔因为您的科技和文化很高而欣赏您。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_EXIT_LEADER_KNM_HERTA_ANY',													'研究你真是浪费我时间。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_LEADER_KNM_HERTA_LAGS_PROGRESS',												'黑塔因为您的科技和文化低而失望。'),

		('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_KNM_HERTA_ANY',								'你们搞得天翻地覆的地方，是我的私人财产。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',			'抱歉。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',			'{LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_KNM_HERTA_ANY}'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',		'嗯。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_LEADER_KNM_HERTA_ANY',								'看你好像很闲，不如过来配合我做个「小」实验吧？'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',				'抱歉。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_AI_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',				'[自动回复]您好，我现在有事不在，一会也不会和您联系。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',			'嗯。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_DONT_SETTLE_NEAR_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',			'这小鬼，脾气还挺大。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_LEADER_KNM_HERTA_ANY',										'别盯着我的人偶看！你的鼻孔很漂亮吗？'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_AI_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',				'抱歉。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_AI_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',				'[自动回复]您好，我现在有事不在，一会也不会和您联系。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',				'嗯。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_SPYING_ON_ME_HUMAN_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',				'哦。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_LEADER_KNM_HERTA_ANY',								'好了好了，别折腾了。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_AI_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',		'抱歉。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_AI_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',		'[自动回复]您好，我现在有事不在，一会也不会和您联系。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_POSITIVE_LEADER_KNM_HERTA_ANY',		'嗯。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_STOP_CONVERTING_MY_CITIES_HUMAN_RESPONSE_NEGATIVE_LEADER_KNM_HERTA_ANY',		'……（人偶没有回应，看来黑塔本人并不在线）'),

		('zh_Hans_CN',	'LOC_LOADING_INFO_LEADER_KNM_ASTA',										 						'艾丝妲，你是黑塔空间站的主心骨，永远心怀对星空的热忱。在你的领导下，空间站不断发展壮大，科学与探索成为了你的指引。星辰的祝福总是与你同在，带领你的人民探索宇宙的奥秘，将文明的边界推向更遥远的星系。无论何时何地，你总能找到正确的方向，因为你相信星星的光芒会照亮未来。'),
		('zh_Hans_CN',	'LOC_AGENDA_KNM_ASTA_NAME',																		'星空祝言'),
		('zh_Hans_CN',	'LOC_AGENDA_KNM_ASTA_DESCRIPTION',																'喜欢 [ICON_Science] 科技值高和乐于探索太空的文明。讨厌 [ICON_Science] 科技值落后的文明。'),
		('zh_Hans_CN',	'LOC_LEADER_KNM_ASTA_QUOTE',																	'持续不断地将资金投入空间站的建设，完善员工福利，形成良性循环，同时满足站长，也就是本人自身必要的购物需求。'),
		('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_LEADER_KNM_ASTA_ANY',														'嗨，我是空间站「黑塔」的站长艾丝妲。要你帮忙的时候，我一定告诉你……你放心，不和你客气。'),
		('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_KNM_ASTA_ANY',										'你来了，之前调试的观测阵列该出结果了，有空一起来看看？'),
		('zh_Hans_CN',	'LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_KNM_ASTA_ANY',								'这儿也能看到星星么？'),
		('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_KNM_ASTA_ANY',									'好呀，这就是「追星之旅」吗？'),
		('zh_Hans_CN',	'LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_KNM_ASTA_ANY',									'今天太晚了。'),
		('zh_Hans_CN',	'LOC_DIPLO_DELEGATION_FROM_AI_LEADER_KNM_ASTA_ANY',												'要一起看星星吗？'),
		('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_KNM_ASTA_ANY',								'我不一定都能帮上忙，但只要是花钱能解决的事，尽管和我说吧。'),
		('zh_Hans_CN',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_KNM_ASTA_ANY',								'我可不记得有邀请过你们。'),
		('zh_Hans_CN',	'LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_KNM_ASTA_ANY',											'星辰会铭记我们的名字。让我们接受星星的祝福吧。'),
		('zh_Hans_CN',	'LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_KNM_ASTA_ANY',									'一切，都是星辰的选择。'),
		('zh_Hans_CN',	'LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_KNM_ASTA_ANY',									'行吧。'),
		('zh_Hans_CN',	'LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_KNM_ASTA_ANY',											'真是不懂礼貌的客人。'),
		('zh_Hans_CN',	'LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_KNM_ASTA_ANY',												'任何人如果觉得自己可以像黑塔女士那样任性妄为，建议他先思考一下自己是否具备黑塔女士那样的智慧。（谴责你）'),
		('zh_Hans_CN',	'LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_KNM_ASTA_ANY',											'哎，就算我不和任何一个人联系，你们这些人也会自个儿找上门来。'),
		('zh_Hans_CN',	'LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_KNM_ASTA_ANY',											'我不打别人，别人就不会打我么？'),
		('zh_Hans_CN',	'LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KNM_ASTA_ANY',													'无法担任空间站站长，这下只能回去继承家业了……'),
		('zh_Hans_CN',	'LOC_DIPLO_DEFEAT_FROM_HUMAN_LEADER_KNM_ASTA_ANY',												'{LOC_DIPLO_DEFEAT_FROM_AI_LEADER_KNM_ASTA_ANY}'),
		('zh_Hans_CN',	'LOC_DIPLO_KUDO_EXIT_LEADER_KNM_ASTA_ANY',														'目标就如星辰一般，并非都是遥不可及哟。'),
		('zh_Hans_CN',	'LOC_DIPLO_KUDO_LEADER_KNM_ASTA_HIGH_SCIENCE',													'艾丝妲因为您对星空的喜爱而高兴。'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_EXIT_LEADER_KNM_ASTA_ANY',													'工作的同时兼顾兴趣爱好，有那么难吗？'),
		('zh_Hans_CN',	'LOC_DIPLO_WARNING_LEADER_KNM_HERTA_LOW_SCIENCE',												'您缺乏探索星空的热情，艾丝妲很失望。'),

		('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_KNM_HERTA_SPACE_STATION_CHAPTER_HISTORY_PARA_1',			'天才俱乐部的黑塔不满足于寻常世界的万物法则，她将目光投向了银河中未解的存在，并期待那些遥远的神秘能够满足自己的好奇心。为此，黑塔主导建立了博物馆式星际舰船，并将它发射至行星轨道，开始了「将一切怪异封印在星空之中」的研究工作。远近闻名的黑塔空间站就此诞生。'),
		('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_KNM_HERTA_SPACE_STATION_CHAPTER_HISTORY_PARA_2',			'时至如今，空间站已经拥有了数不胜数的奇物「藏品」，是一座名副其实的星空博物馆。大量的随舰研究人员也都定居于此，他们不断地从银河各处收集遗器和奇物，记录它们的形致与功能，建立起系统的观测与研究方法…最终从谜题中找出更加费解的谜题。这也正是黑塔的最初的目的。'),
		('zh_Hans_CN',	'LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_KNM_HERTA_SPACE_STATION_CHAPTER_HISTORY_PARA_3',			'数量众多的「藏品」常常招来嫉妒的目光，各种势力在暗中摩拳擦掌。凭借着黑塔的实力，空间站很少陷入真正的危机，收藏和研究工作仍在有条不紊地进行之中。'),
		('zh_Hans_CN',	'LOC_PEDIA_LEADERS_PAGE_LEADER_KNM_HERTA_CHAPTER_HISTORY_PARA_1',									'空间站「黑塔」真正的主人。身为湛蓝星智商最高的人类，只做自己感兴趣的事，一旦失去兴趣就立刻走人——空间站就是最好的例子。'),
		('zh_Hans_CN',	'LOC_PEDIA_LEADERS_PAGE_LEADER_KNM_ASTA_CHAPTER_HISTORY_PARA_1',									'好奇心与精力都很旺盛的少女，空间站「黑塔」的名义站长。无论是管理各抒己见的科员，还是直接又不失礼貌地回复博识学会的种种刁难，对艾丝妲来说都易如反掌。毕竟指挥空间站……总比继承家业简单吧！'),
		('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_KNM_HERTA_PUPPET_CHAPTER_HISTORY_PARA_1',								'黑塔用来在世界中进行交流和操作的工具。这些人偶具有她的外貌特征，并且通过她的远程操控进行活动。'),
		('zh_Hans_CN',	'LOC_PEDIA_UNITS_PAGE_UNIT_KNM_HERTA_PUPPET_CHAPTER_HISTORY_PARA_2',								'「好看当然是好看的，但跟我小时候比，勉强七分相似吧。」黑塔如是评价。');

